"""persist the reconciliation cleared balance

Revision ID: 9fd5e6bbcad0
Revises: 3c02cd825ba9
Created: 2026-08-13 10:32:58.262393+00:00

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.models.types

revision: str = "9fd5e6bbcad0"
down_revision: str | None = "3c02cd825ba9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cleared_balance", app.models.types.Money(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.drop_column("cleared_balance")

    # ### end Alembic commands ###
