"""turns and turn steps

Revision ID: 91a397571979
Revises: 9fd5e6bbcad0
Created: 2026-08-13 12:56:19.934772+00:00

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.support.rls import apply_tenant_policies
import app.models.types

revision: str = "91a397571979"
down_revision: str | None = "9fd5e6bbcad0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turns",
        sa.Column("unit_id", app.models.types.GUID(), nullable=False),
        sa.Column("property_id", app.models.types.GUID(), nullable=False),
        sa.Column("move_out_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "in_progress",
                "ready",
                "cancelled",
                name="turnstatus_enum",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("target_ready_on", sa.Date(), nullable=True),
        sa.Column("ready_on", sa.Date(), nullable=True),
        sa.Column("estimated_cost", app.models.types.Money(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("org_id", app.models.types.GUID(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("updated_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("deleted_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("deleted_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("delete_reason", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "ready_on IS NULL OR started_on IS NULL OR ready_on >= started_on",
            name=op.f("ck_turns_ready_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["move_out_id"],
            ["move_outs.id"],
            name=op.f("fk_turns_move_out_id_move_outs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_turns_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_turns_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_turns_unit_id_units"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turns_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_move_out_id"), ["move_out_id"], unique=False)
        batch_op.create_index("ix_turns_org_created", ["org_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_org_id"), ["org_id"], unique=False)
        batch_op.create_index("ix_turns_org_status", ["org_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_property_id"), ["property_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_ready_on"), ["ready_on"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_started_on"), ["started_on"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_turns_target_ready_on"), ["target_ready_on"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_turns_unit_id"), ["unit_id"], unique=False)

    op.create_table(
        "turn_steps",
        sa.Column("turn_id", app.models.types.GUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("trade", sa.String(length=60), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                "skipped",
                name="stepstatus_enum",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("work_order_id", app.models.types.GUID(), nullable=True),
        sa.Column("completed_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("completed_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("skip_reason", sa.String(length=255), nullable=True),
        sa.Column("org_id", app.models.types.GUID(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("updated_by_id", app.models.types.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_turn_steps_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_turn_steps_turn_id_turns"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_turn_steps_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turn_steps")),
        sa.UniqueConstraint("turn_id", "sequence", name="uq_turn_steps_sequence"),
    )
    with op.batch_alter_table("turn_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turn_steps_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_turn_steps_org_created", ["org_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_turn_steps_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_turn_steps_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_turn_steps_turn_id"), ["turn_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_turn_steps_work_order_id"), ["work_order_id"], unique=False
        )

    # ### end Alembic commands ###

    # Two new tenant tables. The original RLS migration only walked the
    # tables that existed when it ran.
    apply_tenant_policies()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turn_steps_work_order_id"))
        batch_op.drop_index(batch_op.f("ix_turn_steps_turn_id"))
        batch_op.drop_index(batch_op.f("ix_turn_steps_status"))
        batch_op.drop_index(batch_op.f("ix_turn_steps_org_id"))
        batch_op.drop_index("ix_turn_steps_org_created")
        batch_op.drop_index(batch_op.f("ix_turn_steps_created_at"))

    op.drop_table("turn_steps")
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turns_unit_id"))
        batch_op.drop_index(batch_op.f("ix_turns_target_ready_on"))
        batch_op.drop_index(batch_op.f("ix_turns_status"))
        batch_op.drop_index(batch_op.f("ix_turns_started_on"))
        batch_op.drop_index(batch_op.f("ix_turns_ready_on"))
        batch_op.drop_index(batch_op.f("ix_turns_property_id"))
        batch_op.drop_index("ix_turns_org_status")
        batch_op.drop_index(batch_op.f("ix_turns_org_id"))
        batch_op.drop_index("ix_turns_org_created")
        batch_op.drop_index(batch_op.f("ix_turns_move_out_id"))
        batch_op.drop_index(batch_op.f("ix_turns_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_turns_created_at"))

    op.drop_table("turns")
    # ### end Alembic commands ###
