"""deposit subledger for trust beneficiaries

Revision ID: 3c02cd825ba9
Revises: 9ef691b1a0aa
Created: 2026-08-11 15:57:18.913794+00:00

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.support.rls import apply_tenant_policies
import app.models.types

revision: str = "3c02cd825ba9"
down_revision: str | None = "9ef691b1a0aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_movements",
        sa.Column("lease_id", app.models.types.GUID(), nullable=False),
        sa.Column("bank_account_id", app.models.types.GUID(), nullable=False),
        sa.Column("amount", app.models.types.Money(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "collected",
                "returned",
                "applied",
                "forfeited",
                "adjustment",
                name="depositmovementkind_enum",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("journal_entry_id", app.models.types.GUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_id", app.models.types.GUID(), nullable=True),
        sa.Column("org_id", app.models.types.GUID(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("updated_by_id", app.models.types.GUID(), nullable=True),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_deposit_movements_amount_non_zero")),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_deposit_movements_bank_account_id_bank_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_deposit_movements_journal_entry_id_journal_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
            name=op.f("fk_deposit_movements_lease_id_leases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_deposit_movements_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deposit_movements")),
    )
    with op.batch_alter_table("deposit_movements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deposit_movements_bank_account_id"), ["bank_account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deposit_movements_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deposit_movements_effective_date"), ["effective_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deposit_movements_journal_entry_id"), ["journal_entry_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deposit_movements_lease_id"), ["lease_id"], unique=False
        )
        batch_op.create_index(
            "ix_deposit_movements_org_account_date",
            ["org_id", "bank_account_id", "effective_date"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_deposit_movements_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            "ix_deposit_movements_org_lease_date",
            ["org_id", "lease_id", "effective_date"],
            unique=False,
        )

    # ### end Alembic commands ###

    # A new tenant table. The original RLS migration only walked the tables
    # that existed when it ran, so without this the deposit subledger - which
    # records whose money is in the trust - would sit outside the isolation
    # boundary while looking entirely correct.
    apply_tenant_policies()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deposit_movements", schema=None) as batch_op:
        batch_op.drop_index("ix_deposit_movements_org_lease_date")
        batch_op.drop_index(batch_op.f("ix_deposit_movements_org_id"))
        batch_op.drop_index("ix_deposit_movements_org_account_date")
        batch_op.drop_index(batch_op.f("ix_deposit_movements_lease_id"))
        batch_op.drop_index(batch_op.f("ix_deposit_movements_journal_entry_id"))
        batch_op.drop_index(batch_op.f("ix_deposit_movements_effective_date"))
        batch_op.drop_index(batch_op.f("ix_deposit_movements_created_at"))
        batch_op.drop_index(batch_op.f("ix_deposit_movements_bank_account_id"))

    op.drop_table("deposit_movements")
    # ### end Alembic commands ###
