"""record the unit status a turn interrupted

Revision ID: 9c56e71f2f93
Revises: 59cd9199a2b7
Created: 2026-08-13 15:02:48.029644+00:00

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c56e71f2f93"
down_revision: str | None = "59cd9199a2b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unit_status_before", sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_column("unit_status_before")

    # ### end Alembic commands ###
