"""signature envelopes

Revision ID: 59cd9199a2b7
Revises: 91a397571979
Created: 2026-08-13 13:07:51.047124+00:00

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.support.rls import apply_tenant_policies
import app.models.types

revision: str = "59cd9199a2b7"
down_revision: str | None = "91a397571979"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signature_envelopes",
        sa.Column("reference", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_id", app.models.types.GUID(), nullable=False),
        sa.Column("document_sha256", sa.String(length=64), nullable=True),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "partially_signed",
                "completed",
                "declined",
                "voided",
                "expired",
                name="envelopestatus_enum",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("sent_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("expires_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("voided_reason", sa.String(length=255), nullable=True),
        sa.Column("org_id", app.models.types.GUID(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("updated_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("deleted_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("deleted_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("delete_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_signature_envelopes_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_signature_envelopes_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signature_envelopes")),
        sa.UniqueConstraint("org_id", "reference", name="uq_signature_envelopes_reference"),
    )
    with op.batch_alter_table("signature_envelopes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_deleted_at"), ["deleted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            "ix_signature_envelopes_org_created", ["org_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signature_envelopes_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            "ix_signature_envelopes_org_status", ["org_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_reference"), ["reference"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signature_envelopes_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_signature_envelopes_subject", ["org_id", "subject_type", "subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_signature_envelopes_subject_type"), ["subject_type"], unique=False
        )

    op.create_table(
        "envelope_signers",
        sa.Column("envelope_id", app.models.types.GUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "signed",
                "declined",
                name="signerstatus_enum",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("signed_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("declined_at", app.models.types.UTCDateTime(), nullable=True),
        sa.Column("decline_reason", sa.String(length=255), nullable=True),
        sa.Column("signed_ip", sa.String(length=45), nullable=True),
        sa.Column("signed_user_agent", sa.String(length=255), nullable=True),
        sa.Column("typed_name", sa.String(length=150), nullable=True),
        sa.Column("consent_text", sa.Text(), nullable=True),
        sa.Column("org_id", app.models.types.GUID(), nullable=False),
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("created_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.types.UTCDateTime(), nullable=False),
        sa.Column("created_by_id", app.models.types.GUID(), nullable=True),
        sa.Column("updated_by_id", app.models.types.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["envelope_id"],
            ["signature_envelopes.id"],
            name=op.f("fk_envelope_signers_envelope_id_signature_envelopes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_envelope_signers_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_envelope_signers")),
        sa.UniqueConstraint("envelope_id", "sequence", name="uq_envelope_signers_sequence"),
    )
    with op.batch_alter_table("envelope_signers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_envelope_signers_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_envelope_signers_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_envelope_signers_envelope_id"), ["envelope_id"], unique=False
        )
        batch_op.create_index(
            "ix_envelope_signers_org_created", ["org_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_envelope_signers_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_envelope_signers_status"), ["status"], unique=False)

    # ### end Alembic commands ###

    # Two new tenant tables.
    apply_tenant_policies()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("envelope_signers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_envelope_signers_status"))
        batch_op.drop_index(batch_op.f("ix_envelope_signers_org_id"))
        batch_op.drop_index("ix_envelope_signers_org_created")
        batch_op.drop_index(batch_op.f("ix_envelope_signers_envelope_id"))
        batch_op.drop_index(batch_op.f("ix_envelope_signers_email"))
        batch_op.drop_index(batch_op.f("ix_envelope_signers_created_at"))

    op.drop_table("envelope_signers")
    with op.batch_alter_table("signature_envelopes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_subject_type"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_subject_id"))
        batch_op.drop_index("ix_signature_envelopes_subject")
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_status"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_reference"))
        batch_op.drop_index("ix_signature_envelopes_org_status")
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_org_id"))
        batch_op.drop_index("ix_signature_envelopes_org_created")
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_external_id"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_expires_at"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_document_id"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_signature_envelopes_created_at"))

    op.drop_table("signature_envelopes")
    # ### end Alembic commands ###
