"""Canonical domain model.

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from app.models.accounting import (
    Account,
    AccountType,
    BankAccount,
    BankAccountType,
    BankTransaction,
    Bill,
    BillLine,
    BillPayment,
    BillStatus,
    ChargeCode,
    FiscalPeriod,
    Invoice,
    InvoiceLine,
    InvoiceStatus,
    JournalEntry,
    JournalLine,
    JournalStatus,
    NormalBalance,
    OwnerDistribution,
    OwnerStatement,
    Payment,
    PaymentApplication,
    PaymentMethod,
    PaymentStatus,
    PeriodStatus,
    Reconciliation,
    ReconciliationException,
    ReconciliationStatus,
)
from app.models.asset_graph import (
    Asset,
    AssetCategory,
    AssetCriticality,
    AssetServiceEvent,
    AssetStatus,
    ServiceEventType,
    Space,
    SpaceKind,
    Warranty,
)
from app.models.audit import (
    AuditAction,
    AuditChainHead,
    AuditEvent,
    AuditOutcome,
    AuditSeverity,
)
from app.models.automation import (
    Approval,
    ApprovalStatus,
    AutomationRule,
    RunStatus,
    StepStatus,
    TriggerType,
    WorkflowRun,
    WorkflowRunStep,
)
from app.models.base import Base, BaseModel, SoftDeleteMixin, TenantModel
from app.models.documents import (
    Document,
    DocumentCategory,
    DocumentLink,
    DocumentShare,
    DocumentVisibility,
    OcrStatus,
    RetentionClass,
    ScanStatus,
)
from app.models.iam import (
    ApiToken,
    LoginAttempt,
    LoginOutcome,
    MfaRecoveryCode,
    PasswordHistory,
    PasswordResetToken,
    Permission,
    Role,
    RoleAssignment,
    RolePermission,
    ScopeType,
    User,
    UserSession,
    UserStatus,
    UserType,
)
from app.models.integration import (
    DeliveryStatus,
    IdempotencyRecord,
    ImportJob,
    ImportStatus,
    InboundEvent,
    IntegrationConnection,
    OutboxEvent,
    WebhookDelivery,
    WebhookEndpoint,
)
from app.models.leasing import (
    Applicant,
    ApplicantRole,
    Application,
    ApplicationStatus,
    ChargeFrequency,
    EmbedForm,
    Lead,
    LeadStatus,
    Lease,
    LeaseCharge,
    LeaseRenewal,
    LeaseStatus,
    MoveOut,
    ScreeningRecommendation,
    ScreeningResult,
    ScreeningStatus,
)
from app.models.maintenance import (
    Inspection,
    InspectionItem,
    InspectionKind,
    InspectionResult,
    InspectionTemplate,
    ItemResult,
    MaintenanceRequest,
    PreventiveMaintenanceSchedule,
    Priority,
    RequestStatus,
    SLAPolicy,
    WorkOrder,
    WorkOrderEvent,
    WorkOrderStatus,
)
from app.models.org import (
    Building,
    Organization,
    OrganizationStatus,
    OwnerEntity,
    OwnershipStake,
    OwnerType,
    Portfolio,
    Property,
    PropertyStatus,
    PropertyType,
    Unit,
    UnitStatus,
)
from app.models.reporting import (
    KpiSnapshot,
    ReportFormat,
    ReportRun,
    ReportStatus,
    ScheduledReport,
)
from app.models.resident import (
    CommunicationChannel,
    Message,
    MessageDirection,
    MessageThread,
    Notice,
    NoticeKind,
    Resident,
    ResidentStatus,
    Tenancy,
    TenancyRole,
)
from app.models.sequences import NumberSequence, SequenceKey
from app.models.vendor import (
    ComplianceKind,
    ComplianceStatus,
    Vendor,
    VendorCompliance,
    VendorStatus,
    VendorTrade,
    VendorType,
)

__all__ = [
    # base
    "Base",
    "BaseModel",
    "SoftDeleteMixin",
    "TenantModel",
    # org
    "Building",
    "Organization",
    "OrganizationStatus",
    "OwnerEntity",
    "OwnerType",
    "OwnershipStake",
    "Portfolio",
    "Property",
    "PropertyStatus",
    "PropertyType",
    "Unit",
    "UnitStatus",
    # iam
    "ApiToken",
    "LoginAttempt",
    "LoginOutcome",
    "MfaRecoveryCode",
    "PasswordHistory",
    "PasswordResetToken",
    "Permission",
    "Role",
    "RoleAssignment",
    "RolePermission",
    "ScopeType",
    "User",
    "UserSession",
    "UserStatus",
    "UserType",
    # audit
    "AuditAction",
    "AuditChainHead",
    "AuditEvent",
    "AuditOutcome",
    "AuditSeverity",
    # leasing
    "Applicant",
    "ApplicantRole",
    "Application",
    "ApplicationStatus",
    "ChargeFrequency",
    "EmbedForm",
    "Lead",
    "LeadStatus",
    "Lease",
    "LeaseCharge",
    "LeaseRenewal",
    "LeaseStatus",
    "MoveOut",
    "ScreeningRecommendation",
    "ScreeningResult",
    "ScreeningStatus",
    # resident
    "CommunicationChannel",
    "Message",
    "MessageDirection",
    "MessageThread",
    "Notice",
    "NoticeKind",
    "Resident",
    "ResidentStatus",
    "Tenancy",
    "TenancyRole",
    # accounting
    "Account",
    "AccountType",
    "BankAccount",
    "BankAccountType",
    "BankTransaction",
    "Bill",
    "BillLine",
    "BillPayment",
    "BillStatus",
    "ChargeCode",
    "FiscalPeriod",
    "Invoice",
    "InvoiceLine",
    "InvoiceStatus",
    "JournalEntry",
    "JournalLine",
    "JournalStatus",
    "NormalBalance",
    "OwnerDistribution",
    "OwnerStatement",
    "Payment",
    "PaymentApplication",
    "PaymentMethod",
    "PaymentStatus",
    "PeriodStatus",
    "Reconciliation",
    "ReconciliationException",
    "ReconciliationStatus",
    # maintenance
    "Inspection",
    "InspectionItem",
    "InspectionKind",
    "InspectionResult",
    "InspectionTemplate",
    "ItemResult",
    "MaintenanceRequest",
    "PreventiveMaintenanceSchedule",
    "Priority",
    "RequestStatus",
    "SLAPolicy",
    "WorkOrder",
    "WorkOrderEvent",
    "WorkOrderStatus",
    # vendor
    "ComplianceKind",
    "ComplianceStatus",
    "Vendor",
    "VendorCompliance",
    "VendorStatus",
    "VendorTrade",
    "VendorType",
    # documents
    "Document",
    "DocumentCategory",
    "DocumentLink",
    "DocumentShare",
    "DocumentVisibility",
    "OcrStatus",
    "RetentionClass",
    "ScanStatus",
    # assets
    "Asset",
    "AssetCategory",
    "AssetCriticality",
    "AssetServiceEvent",
    "AssetStatus",
    "ServiceEventType",
    "Space",
    "SpaceKind",
    "Warranty",
    # automation
    "Approval",
    "ApprovalStatus",
    "AutomationRule",
    "RunStatus",
    "StepStatus",
    "TriggerType",
    "WorkflowRun",
    "WorkflowRunStep",
    # integration
    "DeliveryStatus",
    "IdempotencyRecord",
    "ImportJob",
    "ImportStatus",
    "InboundEvent",
    "IntegrationConnection",
    "OutboxEvent",
    "WebhookDelivery",
    "WebhookEndpoint",
    # reporting
    "KpiSnapshot",
    "ReportFormat",
    "ReportRun",
    "ReportStatus",
    "ScheduledReport",
    # sequences
    "NumberSequence",
    "SequenceKey",
]
